# Project
site_name: OEFamily Trainings
site_url:
site_description: A collection of training modules and tutorials for the Open Energy Family

# Repository
repo_name: OpenEnergyPlatform/tutorial
repo_url: https://github.com/OpenEnergyPlatform/tutorial
docs_dir: docs

# Configuration
theme:
    name: material
    locale: en
    include_sidebar: false
    palette:
      # Palette toggle for light mode
      - scheme: default
        toggle:
          icon: material/brightness-7
          name: Switch to dark mode
      # Palette toggle for dark mode
      - scheme: slate
        toggle:
          icon: material/brightness-4
          name: Switch to light mode

    icon:
    features:
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.indexes
      - navigation.path
      - navigation.tracking
      - navigation.footer
      - navigation.top
      - toc.follow
      - search.suggest
      - search.share


# Extensions
markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: 💙

plugins:
  - mkdocs-jupyter:
      include_source: True
  - search:
      lang: de
  - mkdocs-oep:
      icon:
        code: fontawesome-solid-code
        text: fontawesome-solid-bookmark
        info: fontawesome-solid-info
        video: fontawesome-solid-play
        mail: fontawesome-solid-envelope
        github: fontawesome-brands-github
      logo:
        sirop: SIROP_logo_50.png
        oep: OEP_logo_2_no_text.svg

extra:
  generator: false

extra_css:
  - css/extra.css
