-- metadata 
COMMENT ON TABLE example.datatable IS '{
    "title": "Conceived Example Table Meant for Creating an Illustrative Metadata String thereof",
    "description": "An imaginary table that provides many features, offering a suitable source for metadata template entries",
    "language": [ "eng"  ],
    "spatial": {
        "location": "",
        "extent": "Berlin",
        "resolution": "1 m"},
    "temporal": {
        "reference_date": "2018-11-13",
        "start": "",
        "end": "",
        "resolution": ""},
    "sources": [
            {"name": "Technical review and evaluation of Issue",
            "description": "Study financed by Organisation describes Issue. The study is authored by Jon Doe and Erika Mustermann",
            "url": "http://dx.doi.org/1.1/j.d.2000.01.001",
            "license": "",
            "copyright": "Publisher"},
            {"name": "Metastudy on Issue",
            "description": "Study financed by State Actor evaluates Issue in regions. The study is authored by Jane Doe and Otto Normal",
            "url": "http://dx.doi.org/2.2/j.d.2022.02.022",
            "license": "",
            "copyright": "Publisher2"}],
    "license": {
        "id": "ODbL-1.0",
        "name": "Open Data Commons Open Database License 1.0",
        "version": "1",
        "url": "https://opendatacommons.org/licenses/odbl/1.0/",
        "instruction": "You are free: To Share, To Create, To Adapt; As long as you: Attribute, Share-Alike, Keep open!",
        "copyright": "Institute"},
    "contributors": [
            {"name": "Person McPeople",
            "email": "person.mcpeople@good-institute.net",
            "date": "2011-1-11",
            "comment": "Prepared the dataset"},
            {"name": "Indivia Menschen",
            "email": "indivia.mensch@gute-organisation.org",
            "date": "2012-2-12",
            "comment": "Fixed Metadata String and date format "},
            {"name": "testuserando",
            "email": "testemailadoo",
            "date": "2018-11-14",
            "comment": "Update metadata to v1.3"}],
    "resources": [
            {"name": "example.datatable",
            "format": "PostgreSQL",
            "fields": [
                {"name": "id",
                "description": "unambiguous unique numer",
                "unit": "none"},
                {"name": "component_id",
                "description": "Identifying numer of component. May repeat due to several occurences of the same component.",
                "unit": "none"},
                {"name": "measurement",
                "description": "Measured by Instrument",
                "unit": "kWh"},
                {"name": "reference",
                "description": "Bibtex String that references the information source.",
                "unit": "none"}]}],
    "metadata_version": "1.3"}';
